//
//  AccountPresenter.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountPresentationLogic {
    func presentAccountAndBalance(_ response: Account.UpdateViews.Response)
}

class AccountPresenter: AccountPresentationLogic {
    
    weak var viewController: AccountDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentAccountAndBalance(_ response: Account.UpdateViews.Response) {
        let viewModel = Account.UpdateViews.ViewModel(accountAddress: response.wallet.accountAddress,
                                                      balance: response.wallet.balance)
        viewController?.displayUpdatedViews(viewModel)
    }
}
