//
//  AccountViewController.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDisplayLogic: class {
    func displayUpdatedViews(_ viewModel: Account.UpdateViews.ViewModel)
}

class AccountViewController: UIViewController {
    
    // MARK: - Properties
    
    var interactor: AccountBusinessLogic?
    var router: AccountRouterInput?
    
    // MARK: - Outlets
    
    @IBOutlet weak var accountAddressLabel: UILabel!
    @IBOutlet weak var balanceLabel: UILabel!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        AccountConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.updateViews()
    }
}

// MARK: Display Logic

extension AccountViewController: AccountDisplayLogic {
    func displayUpdatedViews(_ viewModel: Account.UpdateViews.ViewModel) {
        accountAddressLabel.text = viewModel.accountAddress
        balanceLabel.text = viewModel.balance
    }
}
