//
//  AccountInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountBusinessLogic {
    func updateViews()
}

protocol AccountDataStore {
    var wallet: Wallet? { get set }
}

class AccountInteractor: AccountBusinessLogic, AccountDataStore {
    
    var wallet: Wallet?
    
    var presenter: AccountPresentationLogic?
    lazy var worker: AccountWorker? = {
        return AccountWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something

    func updateViews() {
        guard let wallet = wallet else { fatalError("Wallet should be initialized by this point.") }
        presenter?.presentAccountAndBalance(Account.UpdateViews.Response(wallet: wallet))
    }
}
