//
//  AccountRouter.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountRoutingNavigation {
    func showNewScreen()
}

protocol AccountDataPassing {
    var dataStore: AccountDataStore? { get set }
    func passDataToNextScene(segue: UIStoryboardSegue)
}

typealias AccountRouterInput = AccountRoutingNavigation & AccountDataPassing

class AccountRouter: AccountRouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = ""
    }
    
    var dataStore: AccountDataStore?
    weak var viewController: AccountViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        viewController?.performSegue(withIdentifier: Segues.ShowNextScreenIdentifier, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
