//
//  AccountInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountBusinessLogic {
    func doSomething(_ request: Account.Something.Request)
}

protocol AccountDataStore {
    //var name: String { get set }
}

class AccountInteractor: AccountBusinessLogic, AccountDataStore {
    
    var presenter: AccountPresentationLogic?
    lazy var worker: AccountWorker? = {
        return AccountWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: Account.Something.Request) {
        worker?.doSomeWork()
        
        let response = Account.Something.Response()
        presenter?.presentSomething(response)
    }
}
