//
//  VerificationViewController.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerificationDisplayLogic: class {
    func displaySomething(_ viewModel: Verification.Something.ViewModel)
}

class VerificationViewController: UIViewController, VerificationDisplayLogic {
    
    // MARK: - Properties
    var interactor: VerificationBusinessLogic?
    var router: VerificationRouterInput?
    
    // Mark: - Outlets
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        VerificationConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: - Do something
    
    func doSomething() {
        let request = Verification.Something.Request()
        interactor?.doSomething(request)
    }
    
    func displaySomething(_ viewModel: Verification.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
