//
//  VerificationModels.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Verification {
    // MARK: Use cases
    
    struct InitialState {
        struct Response {
            let onTextDidChangeClosure: (String) -> Void
            let textValidator: TextValidator
        }
        
        struct ViewModel {
            let validationConfiguration: ValidationConfiguration
            let buttonStyle: UIViewStyle<UIButton>
        }
    }
    
    struct ValidationChange {
        struct Response {
            let validationState: ValidationState
        }
        
        struct ViewModel {
            let buttonStyle: UIViewStyle<UIButton>
        }
    }
    
    struct Verify {
        struct Request {
            let verificationMessage: String
        }
    }
}
