//
//  VerificationInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerificationBusinessLogic {
    func doSomething(_ request: Verification.Something.Request)
}

protocol VerificationDataStore {
    //var name: String { get set }
}

class VerificationInteractor: VerificationBusinessLogic, VerificationDataStore {
    
    var presenter: VerificationPresentationLogic?
    lazy var worker: VerificationWorker? = {
        return VerificationWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: Verification.Something.Request) {
        worker?.doSomeWork()
        
        let response = Verification.Something.Response()
        presenter?.presentSomething(response)
    }
}
