//
//  VerificationPresenter.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerificationPresentationLogic {
    func presentInitialState(_ response: Verification.InitialState.Response)
    func presentValidationDidChange(_ response: Verification.ValidationChange.Response)
    func presentVerification()
}

class VerificationPresenter: VerificationPresentationLogic {
    
    private struct Constants {
        static let ButtonTitle: String = "Verify"
    }
    
    weak var viewController: VerificationDisplayLogic?
    
    private var buttonStyleHandler: (ValidationState) -> UIViewStyle<UIButton> = { validationState in
        return UIViewStyle<UIButton> { button in
            var isEnabled: Bool = false
            
            switch validationState {
            case .none, .invalid:
                button.backgroundColor = .lightGray
            case .valid:
                isEnabled = true
                button.backgroundColor = .systemBlue
            }
            
            button.setTitleColor(.white, for: .normal)
            button.setTitle(Constants.ButtonTitle, for: .normal)
            button.isEnabled = isEnabled
        }
    }
    
    // MARK: Presentation Logic
    
    func presentInitialState(_ response: Verification.InitialState.Response) {
        let validationConfiguration = ValidationConfiguration(textValidator: response.textValidator, onTextDidChangeCompletion: response.onTextDidChangeClosure)
        let viewModel = Verification.InitialState.ViewModel(validationConfiguration: validationConfiguration, buttonStyle: buttonStyleHandler(.none))
        viewController?.displayInitialState(viewModel)
    }
    
    func presentValidationDidChange(_ response: Verification.ValidationChange.Response) {
        let viewModel = Verification.ValidationChange.ViewModel(buttonStyle: buttonStyleHandler(response.validationState))
        viewController?.displayValidationDidChange(viewModel)
    }
    
    func presentVerification() {
        viewController?.displayVerification()
    }
}
