//
//  QRCodeScannerWorker.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import AVFoundation
import UIKit

class QRCodeScannerWorker {
    
    private var captureDevice: AVCaptureDevice? = {
        guard let captureDevice = AVCaptureDevice.default(for: AVMediaType.video) else {
            assertionFailure("Failed to get the camera device")
            return nil
        }

        return captureDevice
    }()
    
    func getInputDevice() -> AVCaptureDeviceInput? {
        guard let captureDevice = captureDevice else { return nil }
        
        do {
            let input = try AVCaptureDeviceInput(device: captureDevice)
            
            return input
        } catch {
            assertionFailure(error.localizedDescription)
            return nil
        }
    }
}
