//
//  QRCodeScannerInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QRCodeScannerBusinessLogic {
    func doSomething(_ request: QRCodeScanner.Something.Request)
}

protocol QRCodeScannerDataStore {
    //var name: String { get set }
}

class QRCodeScannerInteractor: QRCodeScannerBusinessLogic, QRCodeScannerDataStore {
    
    var presenter: QRCodeScannerPresentationLogic?
    lazy var worker: QRCodeScannerWorker? = {
        return QRCodeScannerWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: QRCodeScanner.Something.Request) {
        worker?.doSomeWork()
        
        let response = QRCodeScanner.Something.Response()
        presenter?.presentSomething(response)
    }
}
