//
//  QRCodeScannerPresenter.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QRCodeScannerPresentationLogic {
    func presentSetupCaptureSession(_ response: QRCodeScanner.CaptureSession.Response)
    func presentQrCodeValidation(_ response: QRCodeScanner.Validation.Response)
}

class QRCodeScannerPresenter: QRCodeScannerPresentationLogic {
    
    weak var viewController: QRCodeScannerDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentSetupCaptureSession(_ response: QRCodeScanner.CaptureSession.Response) {
        viewController?.displayCaptureSession(response)
    }
    
    func presentQrCodeValidation(_ response: QRCodeScanner.Validation.Response) {
        let title: String
        switch response.result {
        case let .success(message):
            title = message
        case let .failure(qrCodeError):
            title = qrCodeError.localizedDescription
        }
        let viewModel = QRCodeScanner.Validation.ViewModel(title: title)
        viewController?.displayQrCodeValidation(viewModel)
    }
}
