//
//  SetupViewController.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupDisplayLogic: class {
    func displayInitialState(_ viewModel: Setup.InitialState.ViewModel)
    func displayAccountAndBalance(_ viewModel: Setup.Account.ViewModel)
}

class SetupViewController: UIViewController {
    
    // MARK: - Properties
    var interactor: SetupBusinessLogic?
    var router: SetupRouterInput?
    private var validationConfiguration: ValidationConfiguration?
    
    // MARK: - Outlets
    
    @IBOutlet weak var privateKeyTextField: UITextField!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        SetupConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        interactor?.requestInitialState()
        
        do {
            try interactor?.createAccount(Setup.Account.Request(privateKeyText: "djoko"))
        } catch {
            print(error.localizedDescription)
        }
    }
    
}

// MARK: - Display Logic

extension SetupViewController: SetupDisplayLogic {
    func displayInitialState(_ viewModel: Setup.InitialState.ViewModel) {
        validationConfiguration = viewModel.validationConfiguration
        validationConfiguration?.setup(privateKeyTextField)
    }
    
    func displayAccountAndBalance(_ viewModel: Setup.Account.ViewModel) {
        router?.showAccountAndBalance()
    }
}

