//
//  SetupInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetupBusinessLogic {
    func doSomething(_ request: Setup.Something.Request)
}

protocol SetupDataStore {
    //var name: String { get set }
}

class SetupInteractor: SetupBusinessLogic, SetupDataStore {
    
    var presenter: SetupPresentationLogic?
    lazy var worker: SetupWorker? = {
        return SetupWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: Setup.Something.Request) {
        worker?.doSomeWork()
        
        let response = Setup.Something.Response()
        presenter?.presentSomething(response)
    }
}
