//
//  SignaturePresenter.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignaturePresentationLogic {
    func presentInitialState(_ response: Signature.InitialState.Response)
}

class SignaturePresenter: SignaturePresentationLogic {
    
    weak var viewController: SignatureDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentInitialState(_ response: Signature.InitialState.Response) {
        let signedMessageLabelStyle = UIViewStyle<UILabel> { label in
            label.text = response.signedMessage
        }
        
        let imageViewStyle = UIViewStyle<UIImageView> { imageView in
            imageView.image = response.qrCodeImage
        }
        
        viewController?.displayInitialState(Signature.InitialState.ViewModel(signedMessageLabelStyle: signedMessageLabelStyle,
                                                                             imageViewStyle: imageViewStyle))
    }
}
