//
//  SignatureWorker.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SignatureWorker {
    
    func generateQRCode(from data: Data?) -> UIImage? {
        guard let data = data else { return nil }
        
        return data.qrCodeImage
    }
}
