//
//  SignatureInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignatureBusinessLogic {
    func requestInitialState()
}

protocol SignatureDataStore {
    var signedMessage: String? { get set }
    var imageData: Data? { get set }
}

class SignatureInteractor: SignatureBusinessLogic, SignatureDataStore {
    
    var signedMessage: String?
    var imageData: Data?
    
    var presenter: SignaturePresentationLogic?
    lazy var worker: SignatureWorker? = {
        return SignatureWorker()
    }()
    
    // MARK: Business Logic
    
    func requestInitialState() {
        presenter?.presentInitialState(Signature.InitialState.Response(signedMessage: signedMessage,
                                                                       qrCodeImage: worker?.generateQRCode(from: imageData)))
    }
}
