//
//  SignatureViewController.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignatureDisplayLogic: class {
    func displayInitialState(_ viewModel: Signature.InitialState.ViewModel)
}

class SignatureViewController: UIViewController {
    
    // MARK: - Properties
    
    var interactor: SignatureBusinessLogic?
    var router: SignatureRouterInput?
    
    // MARK: - Outlets
    
    @IBOutlet weak var signedMessageLabel: UILabel!
    @IBOutlet weak var qrCodeImageView: UIImageView!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        SignatureConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.requestInitialState()
    }
}

extension SignatureViewController: SignatureDisplayLogic {
    func displayInitialState(_ viewModel: Signature.InitialState.ViewModel) {
        viewModel.signedMessageLabelStyle.apply(to: signedMessageLabel)
        viewModel.imageViewStyle.apply(to: qrCodeImageView)
    }
}
