//
//  SigningInteractor.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SigningBusinessLogic {
    func doSomething(_ request: Signing.Something.Request)
}

protocol SigningDataStore {
    //var name: String { get set }
}

class SigningInteractor: SigningBusinessLogic, SigningDataStore {
    
    var presenter: SigningPresentationLogic?
    lazy var worker: SigningWorker? = {
        return SigningWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: Signing.Something.Request) {
        worker?.doSomeWork()
        
        let response = Signing.Something.Response()
        presenter?.presentSomething(response)
    }
}
