//
//  SigningRouter.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SigningRoutingNavigation {
    func showSignature()
}

protocol SigningDataPassing {
    var dataStore: SigningDataStore? { get set }
    func passDataToNextScene(segue: UIStoryboardSegue)
}

typealias SigningRouterInput = SigningRoutingNavigation & SigningDataPassing

class SigningRouter: SigningRouterInput {
    
    private struct Segues {
        static let ShowSignatureIdentifier = "showSignature"
    }
    
    var dataStore: SigningDataStore?
    weak var viewController: SigningViewController?
    
    // MARK: Navigation
    
    func showSignature() {
        viewController?.performSegue(withIdentifier: Segues.ShowSignatureIdentifier, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowSignatureIdentifier,
            let signatureViewController = segue.destination as? SignatureViewController {
            
            signatureViewController.router?.dataStore?.signedMessage = dataStore?.signedMessage
            signatureViewController.router?.dataStore?.imageData = dataStore?.imageData
        }
    }
}
