//
//  SigningViewController.swift
//  EthereumSigner
//
//  Created by Djordje Ljubinkovic on 08/02/2020.
//  Copyright (c) 2020 Djordje Ljubinkovic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SigningDisplayLogic: class {
    func displaySignedMessage(_ viewModel: Signing.Signature.ViewModel)
}

class SigningViewController: UIViewController {
    
    // MARK: - Properties
    
    var interactor: SigningBusinessLogic?
    var router: SigningRouterInput?
    
    // MARK: - Outlets
    
    @IBOutlet weak var signMessageTextField: UITextField!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        SigningConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        handleKeyboard()
        hideKeyboardWhenTappedAround()
    }
    
    // MARK: - Actions
    
    @IBAction func signMessageTapped(_ sender: UIButton) {
        guard let text = signMessageTextField.text else { return }
        print("CURR TEXT: \(text)")
        interactor?.signMessage(Signing.Signature.Request(signedMessage: text))
    }
}

extension SigningViewController: SigningDisplayLogic {
    func displaySignedMessage(_ viewModel: Signing.Signature.ViewModel) {
        router?.showSignature()
    }
}
